apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: uppy-server
  namespace: uppy
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: uppy-server
    spec:
      containers:
      - image: docker.io/transloadit/uppy-server:latest
        imagePullPolicy: Always
        name: uppy-server        
        resources:
          limits:
            cpu: 0.5
            memory: 150Mi
          requests:
            cpu: 0.3
            memory: 100Mi
        envFrom:
        - configMapRef:
            name: uppy-server-env
        ports:
        - containerPort: 3020
        volumeMounts:
        - name: uppy-server-data
          mountPath: /mnt/uppy-server-data
      volumes:
      - name: uppy-server-data
        persistentVolumeClaim:
          claimName: uppy-server
